#!/bin/bash
rm -f /var/containers/Shared/SystemGroup/systemgroup.com.apple.mobilegestaltcache/Library/Caches/com.apple.MobileGestalt.plist
rm -f /var/mobile/Library/Caches/com.apple.MobileGestalt.plist
nohup bash -c "ldrestart &" >/dev/null 2>&1
exit 0